version: "2"

services:
  backend:
    container_name: jpayments_backend
    build: .
    environment:
      - ROOT_PATH=/
      - POSTGRES_HOST=base
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - EMAIL_ENABLED=True
      - EMAIL_SERVER=smtp4dev
      - EMAIL_PORT=25
      - EMAIL_FROM=noreply@smtp4dev.lan
      - EMAIL_FROM_NAME=oreply@smtp4dev.lan
      - EMAIL_PASSWORD=noreply
      - EMAIL_TEMPLATES_DIR=/email_templates
    ports:
      - "80:8000"
    depends_on:
      - base
    volumes:
      - ./email_templates:/email_templates
      - ./secrets:/secrets
  base:
    container_name: jpayments_base
    image: "postgres:13"
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PORT=5432
  pgweb:
    container_name: jpayments_pgweb
    image: sosedoff/pgweb
    restart: always
    environment:
        - DATABASE_URL=postgres://postgres:postgres@base:5432/postgres?sslmode=disable
    depends_on:
      - base
  smtp4dev:
    container_name: jpayments_smtp4dev
    image: rnwood/smtp4dev
    volumes:
        - ./smtp4dev-data:/smtp4dev
    ports:
      - "88:80"