version: "2"

services:
  backend:
    container_name: jpayments_backend
    build: .
    environment:
      - POSTGRES_HOST=base
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - base
    volumes:
      - ./secrets:/secrets
  base:
    container_name: jpayments_base
    image: "postgres:13"
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PORT=5432
  pgweb:
    container_name: jpayments_pgweb
    image: sosedoff/pgweb
    restart: always
    environment:
        - PGWEB_DB_URL=postgres://postgres:postgres@base:5432/postgres
    depends_on:
      - base
  nginx:
    container_name: jpayments_nginx
    image: nginx:1.23.2
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend